spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: h2
  datasource:
    url: jdbc:h2:file:~/temp/data/testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}